added isEven files
autolab/autograders-examples pull request #15
Opened 2024-01-27 20:51 UTC by jhs-panda

- Created autograder for function that determines if an input integer is even or not
- Randomly generated integer values as test cases

2024-02-12 18:45 UTC, jlge requested changes
Tested autograder on Nightly and it works 👍. The repo should have a `README.md` describing the contents of the isEven assessment (e.g. the image, scenario, handin format, directory content, and also the problems that need to be defined). Also, kind of nitpicky, it's not really necessary to have a tar file for the handin since the student would only be submitting one file, so you could just set that as the handin file instead. 

The directory should only contain the `autograde-Makefile`, `autograde.tar`, and the untarred contents of `autograde.tar`, so clean up those respective files as well!

2024-02-12 18:45 UTC, jlge commented on Python-isEven/Dockerfile
> +
It would be good to add an instruction here on how to build the Dockerfile, e.g. `docker build -t autograding_iseven .`

2024-02-12 18:45 UTC, jlge commented on Python-isEven/Makefile
I don't think this file is needed

2024-02-12 18:45 UTC, jlge commented on Python-isEven/Python-isEven-handout/driver.py
> +print("{\"scores\": {\"Correctness\": %s}}" % correctness)
nit: add newline

2024-02-12 18:45 UTC, jlge commented on Python-isEven/Python-isEven-handout/tests.py
> +]
nit: add newline

2024-02-12 18:45 UTC, jlge commented on Python-isEven/autograde-Makefile
> +		rm -rf *~ src
nit: add newline

2024-02-12 18:45 UTC, jlge commented on Python-isEven/src/driver.py
> +print("{\"scores\": {\"Correctness\": %s}}" % correctness)
nit: add newline

2024-03-18 16:50 UTC, jlge requested changes
Since the directory structure changed from removing files, `autograde-Makefile` also needs to be edited so that it can run the grader

2024-03-18 17:47 UTC, jhs-panda commented on Python-isEven/autograde-Makefile
> +		rm -rf *~ src
Referred to past examples, decided not to change.

2024-03-18 17:50 UTC, jhs-panda commented
> Since the directory structure changed from removing files, `autograde-Makefile` also needs to be edited so that it can run the grader

Added handin.py file in src folder to simulate a handin file and edited autograde-Makefile accordingly.

2024-03-18 18:06 UTC, jlge approved these changes
LGTM 🤩

2024-03-18 18:09 UTC, merged