cpp fib autograder
autolab/autograders-examples pull request #2
Opened 2022-02-06 20:53 UTC by Huahan98

2022-02-07 21:42 UTC, xinyis991105 commented on Cpp-fibonacci/autograde-Makefile
> +	tar xvf autograder.tar
autograder.tar -> autograde.tar

2022-02-10 19:02 UTC, Huahan98 commented on Cpp-fibonacci/autograde-Makefile
> +	tar xvf autograder.tar
fixed

2022-02-10 20:23 UTC, xinyis991105 requested changes
See my other comment for file autograde-Makefile

2022-02-10 20:23 UTC, xinyis991105 commented on Cpp-fibonacci/autograde-Makefile
> +	(cd test_autograder; make clean; make)
See the autograding feedback at https://autolab-dev.andrew.cmu.edu/courses/15213-s21/assessments/cppfiblab/viewFeedback?feedback=510&submission_id=2103. I think calling a second make leaves the scoring JSON overridden with Makefile's leaving directory statement. Can you find a way around this? Maybe for the inner Makefile just compile, and then call the test program from the outer Makefile?

2022-02-15 21:05 UTC, xinyis991105 approved these changes
LGTM! Good job!

2022-02-15 21:05 UTC, merged