Add valid parenthesis lab
autolab/autograders-examples pull request #7
Opened 2023-01-18 01:35 UTC by evanyeyeye

2023-01-22 04:26 UTC, damianhxy requested changes
Successfully autograded a submission

Left some comments but otherwise LGTM

2023-01-22 04:26 UTC, damianhxy commented on Cvalidparen/Dockerfile
> +# Run: docker build -t autograding_validparen
Seems to be missing a `.` at the end, i.e. `docker build -t autograding_validparen`

2023-01-22 04:26 UTC, damianhxy commented on Cvalidparen/Cvalidparen.yml
> +---
For the purposes of this repository, `Cvalidparen.yml` and `Cvalidparen.rb` are not needed and should be removed

2023-01-26 21:33 UTC, 20wildmanj commented on Cvalidparen/Cvalidparen.rb
> +end
Nit: could you add newlines to the end of files such as here

2023-01-27 14:48 UTC, michellexliu reviewed
could you include the tar as well (similar to how there's a hello.tar in https://github.com/autolab/autograders-examples/tree/main/hellotar)

2023-03-27 01:29 UTC, damianhxy approved these changes
successfully built autograder image, installed assessment, and submitted solution

lgtm!

2023-03-27 01:42 UTC, merged